baseURL: https://blog.kirillov.cc/
languageCode: en-GB
title: Roman's blog
theme: hacked-maverick
staticDir:
  - content/static
permalinks:
  pages: /:slug
params:
  logo: /assets/favicon.ico
  description: Roman's musings
  author: Roman Kirillov
menu:
  main:
    # - identifier: about
    #   name: About
    #   url: /about/
    #   weight: "-110"
    - identifier: posts
      name: Post
      url: /posts/
      weight: -200
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    noHl: false
    style: monokailight
    tabWidth: 4
taxonomies:
  tag: tags
outputs:
  home:
    - HTML
    - RSS
    - JSON
  section:
    - HTML

markup:
  highlight:
    guessSyntax: false

outputFormats:
  RSS:
    mediatype: application/rss
    baseName: atom
  JSON:
    mediatype: application/json
    baseName: feed
    ignoreErrors:
      - error-remote-getjson
